# Generated by Django 4.2.4 on 2023-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="interactive",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
