# Generated by Django 4.2.4 on 2023-08-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_interactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="html_path",
            field=models.CharField(default="", max_length=100),
        ),
    ]
